const USER = {
    LOAD: "REQUEST_USERS_DATA",
    LOAD_SUCCESS: "RECEIVE_USERS_DATA",
    LOAD_USER_DETAIL: "REQUEST_USERS_DETAIL_DATA",
    LOAD_USER_DETAIL_SUCCESS: "RECEIVE_USERS_DETAIL_DATA",

  };
  
  export default USER;